apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-dev-fe
  namespace: bookstore-dev
  labels:
    app: bookstore-dev-fe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookstore-dev-fe
  template:
    metadata:
      labels:
        app: bookstore-dev-fe
    spec:
      containers:
      - name: bookstore-dev-fe
        image: mwakazi/bookstore-dev-fe:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80
