apiVersion: v1
kind: Service
metadata:
  name: bookstore-dev-fe-nodeport
  namespace: bookstore-dev
  labels:
    app: bookstore-dev-fe
spec:
  selector:
    app: bookstore-dev-fe
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30083  # Can be any unused port in 30000-32767
  type: NodePort
