apiVersion: v1
kind: Service
metadata:
  name: bookstore-dev-api-nodeport
  namespace: bookstore-dev
  labels:
    app: bookstore-dev-api
spec:
  selector:
    app: bookstore-dev-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30082
  type: NodePort
