apiVersion: v1
kind: Service
metadata:
  name: reddit-api-nodeport
  namespace: reddit
  labels:
    app: reddit-api
spec:
  selector:
    app: reddit-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080  # Can be any unused port in 30000-32767
  type: NodePort
