apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: bookstore-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: copy-init-sql
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /docker-entrypoint-initdb.d && \
              echo "$INIT_SQL" > /docker-entrypoint-initdb.d/init.sql
          env:
            - name: INIT_SQL
              valueFrom:
                configMapKeyRef:
                  name: bookstore-dev-configmap
                  key: init.sql
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: bookstore_dev_db
            - name: POSTGRES_USER
              value: bookstore_dev_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookstore-dev-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: bookstore-pvc
        - name: init-script
          emptyDir: {}
