apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-dev-api
  namespace: bookstore-dev
  labels:
    app: bookstore-dev-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookstore-dev-api
  template:
    metadata:
      labels:
        app: bookstore-dev-api
    spec:
      containers:
      - name: bookstore-dev-api
        image: mwakazi/bookstore-dev-api:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: postgres.bookstore-dev.svc.cluster.local
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: bookstore-dev-configmap
              key: POSTGRES_DB
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: bookstore-dev-configmap
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstore-dev-secrets
              key: POSTGRES_PASSWORD
