apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-api
  namespace: reddit
  labels:
    app: reddit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-api
  template:
    metadata:
      labels:
        app: reddit-api
    spec:
      containers:
      - name: reddit-api
        image: mwakazi/reddit-api:staging
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql.reddit.svc.cluster.local:3306/${MYSQL_DATABASE}


        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: com.mysql.cj.jdbc.Driver

        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: reddit-configmap
              key: MYSQL_USER

        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reddit-secrets
              key: MYSQL_PASSWORD

        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: reddit-configmap
              key: MYSQL_DATABASE
