apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: reddit
  labels:
    app: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql # 📝 Make sure this directory exists on the host