---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: reddit
  labels:
    app: mysql
    tier: database
    version: v1
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306