name: Minimal Runner Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Echo something
        run: echo "✅ Hello from self-hosted runner"



# name: Deploy to Kubernetes
# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: "self-hosted"
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

      # - name: Apply PersistentVolume
      #   run: kubectl apply -f database/PersistentVolume.yml --validate=false

      # - name: Apply PersistentVolumeClaim
      #   run: kubectl apply -f database/PersistentVolumeClaim.yml --validate=false

      # - name: Apply MySQL deployment
      #   run: kubectl apply -f database/deployment.yml --validate=false

      # - name: Apply MySQL service
      #   run: kubectl apply -f database/service.yml --validate=false
