name: Reddit Database Deployment
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    timeout-minutes: 12
    runs-on: [self-hosted]
    env:
      KUBECTL_VERSION: v1.33.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test kubectl access
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{secrets.KUBE_CONFIG_DATA_K8S}}
          version: ${{ env.KUBECTL_VERSION }}
          command: kubectl get nodes

      # - name: Apply PersistentVolume
      #   run: kubectl apply -f database/PersistentVolume.yml --validate=false

      # - name: Apply PersistentVolumeClaim
      #   run: kubectl apply -f database/PersistentVolumeClaim.yml --validate=false

      # - name: Apply MySQL deployment
      #   run: kubectl apply -f database/deployment.yml --validate=false

      # - name: Apply MySQL service
      #   run: kubectl apply -f database/service.yml --validate=false
