name: Deploy MySQL Database Changes

on:
  push:
    branches: [main]
    paths:
      - 'database/**'

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      database: ${{ steps.filter.outputs.database }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            database:
              - 'database/**'

  deploy-mysql:
    runs-on: self-hosted
    needs: filter
    if: needs.filter.outputs.database == 'true'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}"
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Apply PersistentVolume
        run: kubectl apply -f database/PersistentVolume.yml

      - name: Apply PersistentVolumeClaim
        run: kubectl apply -f database/PersistentVolumeClaim.yml

      - name: Apply MySQL deployment
        run: kubectl apply -f database/deployment.yml

      - name: Apply MySQL service
        run: kubectl apply -f database/service.yml
