name: Deploy MySQL Database Changes

on:
  push:
    branches: [main]
    paths:
      - 'database/**'

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      database: ${{ steps.filter.outputs.database }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            database:
              - 'database/**'

  deploy-mysql:
    runs-on: [self-hosted, Linux, X64]
    needs: filter
    if: needs.filter.outputs.database == 'true'
    env:
      KUBECONFIG: $HOME/.kube/config
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.DOCKER_HUB_TOKEN}}"
          echo "${{ secrets.KUBE_CONFIG_DATA_K8S }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          export KUBECONFIG=$HOME/.kube/config


      - name: Test kubectl access
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl get nodes

      - name: Apply PersistentVolume
        run: kubectl apply -f database/PersistentVolume.yml --validate=false

      - name: Apply PersistentVolumeClaim
        run: kubectl apply -f database/PersistentVolumeClaim.yml --validate=false

      - name: Apply MySQL deployment
        run: kubectl apply -f database/deployment.yml --validate=false

      - name: Apply MySQL service
        run: kubectl apply -f database/service.yml --validate=false
