name: Deploy MySQL Database Changes

on:
  push:
    branches: [main]
    paths:
      - 'database/**'

jobs:
  filter:
    runs-on: [self-hosted, Linux, X64]
    outputs:
      database: ${{ steps.filter.outputs.database }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            database:
              - 'database/**'

  deploy-mysql:
    runs-on: [self-hosted, Linux, X64]
    needs: filter
    env:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    if: needs.filter.outputs.database == 'true'
    env:
      KUBECONFIG: $HOME/.kube/config
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Test kubectl access
        run: |
          kubectl get nodes

      - name: Apply PersistentVolume
        run: kubectl apply -f database/PersistentVolume.yml --validate=false

      - name: Apply PersistentVolumeClaim
        run: kubectl apply -f database/PersistentVolumeClaim.yml --validate=false

      - name: Apply MySQL deployment
        run: kubectl apply -f database/deployment.yml --validate=false

      - name: Apply MySQL service
        run: kubectl apply -f database/service.yml --validate=false
