name: Deploy MySQL on Database Changes

on:
  push:
    branches: [staging]
    paths:
      - 'database/**'

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      database: ${{ steps.filter.outputs.database }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Filter for /database changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            database:
              - 'database/**'

  deploy-mysql:
    name: Apply MySQL K8s Resources
    needs: filter
    if: needs.filter.outputs.database == 'true'
    runs-on: self-hosted  # ✅ this targets your local runner
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA_K8S }}" > ~/.kube/config

      - name: Apply PersistentVolume
        run: |
          kubectl apply -f database/PersistentVolume.yml

      - name: Apply PersistentVolumeClaim
        run: |
          kubectl apply -f database/PersistentVolumeClaim.yml

      - name: Apply MySQL pod deployment
        run: |
          kubectl apply -f database/deployment.yml

      - name: Apply MySQL Service
        run: |
          kubectl apply -f database/service.yml