name: Database deployment to Kubernetes

on:
  push:
    branches:
      - main
    paths:
      - 'database/**'

jobs:
  deploy:
    runs-on: self-hosted  # ✅ Runs on your local runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubeconfig from secret (plaintext)
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA_K8S }}" > ~/.kube/config

    - name: Apply mysql-deployment.yml if any /database file changed
      run: |
        CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^database/' || true)

        if [ -z "$CHANGED" ]; then
          echo "✅ No changes in database/, skipping apply."
          exit 0
        fi

        echo "🚀 Detected changes in database/. Applying mysql-deployment.yml"
        kubectl apply -f database/mysql-deployment.yml
